# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

ifeq ($(config),debug)
TARGETDIR = bin/Debug
TARGET = $(TARGETDIR)/LinuxBuild
  define BUILDCMDS
	@echo Running build commands
	wsl.exe bash Scripts/wsl-build.sh
  endef
  define CLEANCMDS
	@echo Running clean commands
	wsl.exe bash Scripts/wsl-clean.sh
  endef

else ifeq ($(config),release)
TARGETDIR = bin/Release
TARGET = $(TARGETDIR)/LinuxBuild
  define BUILDCMDS
	@echo Running build commands
	wsl.exe bash Scripts/wsl-build.sh
  endef
  define CLEANCMDS
	@echo Running clean commands
	wsl.exe bash Scripts/wsl-clean.sh
  endef

else ifeq ($(config),dist)
TARGETDIR = bin/Dist
TARGET = $(TARGETDIR)/LinuxBuild
  define BUILDCMDS
	@echo Running build commands
	wsl.exe bash Scripts/wsl-build.sh
  endef
  define CLEANCMDS
	@echo Running clean commands
	wsl.exe bash Scripts/wsl-clean.sh
  endef

else
  $(error "invalid configuration $(config)")
endif

$(TARGET):
	$(BUILDCMDS)

clean:
	$(CLEANCMDS)
