"""Embeds the AMD FidelityFX FSR 1 SDK headers (ffx_a.h, ffx_fsr1.h) as C++ string chunks so the engine can compile
them into its GLSL shaders without reading files at runtime.

Run it again after updating the SDK:  python Scripts/embed_fsr_sdk.py

Output: NetTFGEngine/Source/OpenGL/Render pipeline/FSR_SDK/FSR1_GLSL.inl
Each header becomes an array of raw string literals, split on line boundaries so no single literal exceeds MSVC's
~16 KB limit; FSR1_GLSL::FfxA() / FfxFsr1() join them back.
"""

from pathlib import Path

SDK_DIR = Path(__file__).resolve().parent.parent / "NetTFGEngine" / "Source" / "OpenGL" / "Render pipeline" / "FSR_SDK"
OUTPUT = SDK_DIR / "FSR1_GLSL.inl"
HEADERS = [("kFfxA", "ffx_a.h"), ("kFfxFsr1", "ffx_fsr1.h")]
DELIM = "FFX_SDK"
MAX_CHUNK = 12000  # bytes per literal, well under MSVC's 16380


def chunks(text: str):
    current, size = [], 0
    for line in text.splitlines(keepends=True):
        if size + len(line) > MAX_CHUNK and current:
            yield "".join(current)
            current, size = [], 0
        current.append(line)
        size += len(line)
    if current:
        yield "".join(current)


def main():
    out = [
        "// GENERATED by Scripts/embed_fsr_sdk.py from ffx_a.h and ffx_fsr1.h. Do not edit; re-run the script instead.",
        "#pragma once",
        "#include <string>",
        "",
        "namespace FSR1_GLSL {",
    ]
    for var, name in HEADERS:
        text = (SDK_DIR / name).read_text(encoding="utf-8").replace("\r\n", "\n")
        end = f"){DELIM}\""
        if end in text:
            raise SystemExit(f"{name} contains the raw string delimiter {end!r}; change DELIM")
        out.append(f"inline const char* const {var}[] = {{")
        for chunk in chunks(text):
            out.append(f"R\"{DELIM}({chunk}){DELIM}\",")
        out.append("};")
        out.append("")
    out += [
        "template <size_t N>",
        "inline void Append(std::string& dst, const char* const (&parts)[N]) { for (const char* p : parts) dst += p; }",
        "",
        "// ffx_a.h followed by ffx_fsr1.h. The caller defines A_GPU/A_GLSL before and FSR_*/callbacks as the SDK asks.",
        "inline std::string FfxA()    { std::string s; Append(s, kFfxA);    return s; }",
        "inline std::string FfxFsr1() { std::string s; Append(s, kFfxFsr1); return s; }",
        "}",
        "",
    ]
    OUTPUT.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
