"""Embeds the NVIDIA Image Scaling SDK shader (NIS_Scaler.h) as C++ string chunks so the engine can compile it into
its OpenGL compute shader without reading files at runtime.

Run it again after updating the SDK:  python Scripts/embed_nis_sdk.py

Output: NetTFGEngine/Source/OpenGL/Render pipeline/NIS_SDK/NIS_GLSL.inl
The SDK's GLSL path targets Vulkan GLSL (separate texture2D + sampler objects combined with sampler2D(tex, s)), which
OpenGL GLSL doesn't have. The texture access macros are rewritten to take plain sampler2D uniforms instead; nothing
else in the algorithm changes. The script fails if any of those lines is no longer found (SDK changed: review them).
Like embed_fsr_sdk.py, the text is split on line boundaries so no single literal exceeds MSVC's ~16 KB limit.
"""

from pathlib import Path

SDK_DIR = Path(__file__).resolve().parent.parent / "NetTFGEngine" / "Source" / "OpenGL" / "Render pipeline" / "NIS_SDK"
OUTPUT = SDK_DIR / "NIS_GLSL.inl"
HEADER = "NIS_Scaler.h"
DELIM = "NIS_SDK"
MAX_CHUNK = 12000  # bytes per literal, well under MSVC's 16380

# Vulkan GLSL -> OpenGL GLSL: x is a sampler2D uniform (linear/clamp sampler object bound on its unit by the engine).
PATCHES = [
    ("#define NVTEX_LOAD(x, pos) texelFetch(sampler2D(x, samplerLinearClamp), pos, 0)",
     "#define NVTEX_LOAD(x, pos) texelFetch(x, pos, 0)"),
    ("#define NVTEX_SAMPLE(x, sampler, pos) textureLod(sampler2D(x, sampler), pos, 0)",
     "#define NVTEX_SAMPLE(x, sampler, pos) textureLod(x, pos, 0)"),
    ("#define NVTEX_SAMPLE_RED(x, sampler, pos) textureGather(sampler2D(x, sampler), pos, 0)",
     "#define NVTEX_SAMPLE_RED(x, sampler, pos) textureGather(x, pos, 0)"),
    ("#define NVTEX_SAMPLE_GREEN(x, sampler, pos) textureGather(sampler2D(x, sampler), pos, 1)",
     "#define NVTEX_SAMPLE_GREEN(x, sampler, pos) textureGather(x, pos, 1)"),
    ("#define NVTEX_SAMPLE_BLUE(x, sampler, pos) textureGather(sampler2D(x, sampler), pos, 2)",
     "#define NVTEX_SAMPLE_BLUE(x, sampler, pos) textureGather(x, pos, 2)"),
]


def chunks(text: str):
    current, size = [], 0
    for line in text.splitlines(keepends=True):
        if size + len(line) > MAX_CHUNK and current:
            yield "".join(current)
            current, size = [], 0
        current.append(line)
        size += len(line)
    if current:
        yield "".join(current)


def main():
    text = (SDK_DIR / HEADER).read_text(encoding="utf-8").replace("\r\n", "\n")
    for old, new in PATCHES:
        if text.count(old) != 1:
            raise SystemExit(f"{HEADER}: expected exactly one {old!r}; the SDK changed, review PATCHES")
        text = text.replace(old, new)
    if not text.endswith("\n"):
        text += "\n"  # the header ends in "#endif" with no newline; whatever the caller appends must start a new line

    end = f"){DELIM}\""
    if end in text:
        raise SystemExit(f"{HEADER} contains the raw string delimiter {end!r}; change DELIM")

    out = [
        "// GENERATED by Scripts/embed_nis_sdk.py from NIS_Scaler.h (texture macros patched for OpenGL GLSL). Do not edit;",
        "// re-run the script instead.",
        "#pragma once",
        "#include <string>",
        "",
        "namespace NIS_GLSL {",
        "inline const char* const kNisScaler[] = {",
    ]
    for chunk in chunks(text):
        out.append(f"R\"{DELIM}({chunk}){DELIM}\",")
    out += [
        "};",
        "",
        "// NIS_Scaler.h. The caller defines the NIS_* options, the constants (kScaleX...) and the in_texture,",
        "// out_texture, coef_scaler and coef_usm uniforms before it, and main() after it.",
        "inline std::string NisScaler() { std::string s; for (const char* p : kNisScaler) s += p; return s; }",
        "}",
        "",
    ]
    OUTPUT.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
